const fs=require('fs'),vm=require('vm'),assert=require('assert');
const path=require('path'),root=__dirname,nodes={};
const node=id=>nodes[id]||(nodes[id]={value:id==='#size'?'2':'All sports',innerHTML:'',textContent:'',hidden:false,disabled:false});
const context=vm.createContext({document:{querySelector:node,querySelectorAll:()=>[],addEventListener:()=>{}},fetch:()=>new Promise(()=>{}),setInterval:()=>{},Date});
for(const file of ['eligibility.js','validation_view.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))vm.runInContext(match[1],context);
const now=Date.now(),leg=id=>({sport:'MLB',gameId:id,playerId:id,player:'<Player '+id+'>',prop:'Hits',platformLine:0.5,probability:0.7,platform:'Sleeper',actionable:true,requiresPlatformReview:true,platformOfferType:'unreported',kickoffSource:'OFFICIAL_SCHEDULE',startTime:new Date(now+3600000).toISOString(),offerObservedAt:new Date(now-1000).toISOString()});
const legs=[leg(1),leg(2)];
context.fixture={updatedAt:new Date(now-1000).toISOString(),sourceStatus:'CURRENT',sports:{MLB:{status:'LIVE_FORECASTS',sourceStatus:'CURRENT'}},picks:[],results:{recorded:0,graded:0,frozenPredictionMetrics:{brier:null}},model:{version:'fixture'},platformFeed:{status:'CONFIGURED',sportStatus:{MLB:{status:'OBSERVED_BOARD'}}},offerCounts:{observed:2,matched:2,missingOfferType:2,missingKickoff:2},offers:legs,slips:{'2':[{probability:0.49,legs}]}};
vm.runInContext('data=fixture;render()',context);
assert.equal(node('#generate').disabled,false);
node('#generate').onclick();
assert(node('#slipCards').innerHTML.includes('49.0%'));
assert(node('#slipCards').innerHTML.includes('Review in Sleeper'));
assert(node('#slipCards').innerHTML.includes('Kickoff verified from official schedule.'));
assert(node('#slipCards').innerHTML.includes('&lt;Player'));
assert(!node('#slipCards').innerHTML.includes('Source-declared standard offer.'));
assert(node('#slipMessage').textContent.includes('2 have an unreported offer type'));
for(const row of legs)row.offerObservedAt=new Date(now-16*60000).toISOString();
vm.runInContext('expireDisplayedSlips()',context);
assert.equal(node('#generate').disabled,true);
assert(!node('#slipCards').innerHTML.includes('49.0%'));
context.fixture.platformFeed.sportStatus.MLB.httpStatus=401;
vm.runInContext('render()',context);
assert(node('#slipMessage').textContent.includes('HTTP 401'));
console.log('Real slip rendering, review flags, escaping, expiry and provider errors passed.');
