const fs=require('fs'),vm=require('vm'),assert=require('assert');
const path=require('path'),root=__dirname,nodes={};
const node=id=>nodes[id]||(nodes[id]={value:id==='#size'?'4':id==='#playerSearch'?'':id==='#playerProp'?'All props':id==='#playerGame'?'All games':id==='#playerMinimum'?'0':'All sports',options:id==='#size'?[2,3,4,5,6,8].map(value=>({value:String(value)})):[],innerHTML:'',textContent:'',hidden:false,disabled:false});
const context=vm.createContext({document:{querySelector:node,querySelectorAll:()=>[],addEventListener:()=>{}},fetch:()=>new Promise(()=>{}),setInterval:()=>{},Date});
for(const file of ['player_view.js','eligibility.js','validation_view.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))vm.runInContext(match[1],context);
const now=Date.now(),leg=id=>({sport:'MLB',gameId:id,playerId:id,player:'<Player '+id+'>',prop:'Hits',platformLine:0.5,probability:0.7,platform:'Sleeper',actionable:true,requiresPlatformReview:true,platformOfferType:'unreported',kickoffSource:'OFFICIAL_SCHEDULE',startTime:new Date(now+3600000).toISOString(),offerObservedAt:new Date(now-1000).toISOString()});
const legs=[leg(1),leg(2)];
context.fixture={updatedAt:new Date(now-1000).toISOString(),sourceStatus:'CURRENT',sports:{MLB:{status:'LIVE_FORECASTS',sourceStatus:'CURRENT'}},picks:[],results:{recorded:0,graded:0,frozenPredictionMetrics:{brier:null}},model:{version:'fixture'},platformFeed:{status:'CONFIGURED',sportStatus:{MLB:{status:'OBSERVED_BOARD',fetchedAtEpoch:now/1000}},nextRefreshAt:new Date(now+3600000).toISOString(),refreshReason:'SCHEDULED'},offerCounts:{observed:5,matched:2,missingOfferType:2,missingKickoff:2,excluded:{unmatched_model_line:2,expired_line:1}},offers:legs,slips:{'2':[{probability:0.49,legs}]}};
vm.runInContext('data=fixture;render()',context);
assert.equal(node('#generate').disabled,false);
assert(node('#slipSupport').innerHTML.includes('2 fresh exact-line offers · 2 players · 2 separate games'));
assert(node('#slipSupport').innerHTML.includes('No probability for that exact line'));
assert(node('#slipSupport').innerHTML.includes('Expired individual lines'));
assert.equal(node('#size').value,'2');
assert.equal(node('#size').options.find(option=>option.value==='4').disabled,true);
assert(node('#feedTiming').textContent.includes('Next matched line expires in'));
assert(node('#feedTiming').textContent.includes('Next automatic board check after'));
node('#generate').onclick();
assert(node('#slipCards').innerHTML.includes('49.0%'));
assert(node('#slipCards').innerHTML.includes('Review in Sleeper'));
assert(node('#slipCards').innerHTML.includes('Kickoff verified from official schedule.'));
assert(node('#slipCards').innerHTML.includes('&lt;Player'));
assert(!node('#slipCards').innerHTML.includes('Source-declared standard offer.'));
assert(node('#slipMessage').textContent.includes('2 have an unreported offer type'));
context.fixture.slips['2'][0].searchComplete=true;node('#generate').onclick();
assert(node('#slipCards').innerHTML.includes('Exact ranking of current matched offers'));
context.fixture.slips['2'][0].searchComplete=false;node('#generate').onclick();
assert(node('#slipCards').innerHTML.includes('Bounded ranking search'));
for(const row of legs)row.offerObservedAt=new Date(now-16*60000).toISOString();
vm.runInContext('expireDisplayedSlips()',context);
assert.equal(node('#generate').disabled,true);
assert(!node('#slipCards').innerHTML.includes('49.0%'));
context.fixture.platformFeed.sportStatus.MLB.httpStatus=401;
vm.runInContext('render()',context);
assert(node('#slipMessage').textContent.includes('HTTP 401'));
context.fixture.platformFeed.refreshMode='PREGAME_WINDOWS';context.fixture.platformFeed.refreshReason='DAILY_BUDGET';vm.runInContext('render()',context);
assert(node('#feedTiming').textContent.includes('Daily allowance used.'));
assert(node('#feedTiming').textContent.includes('Checks target upcoming game windows.'));
assert(node('#slipSupport').innerHTML.includes('0 fresh exact-line offers · 0 players · 0 separate games'));
context.fixture.sports.MLB.gradingStatus='PARTIAL_RESULT_SOURCE';context.fixture.sports.MLB.gradingGamesUnavailable=1;vm.runInContext('render()',context);
assert(node('#gradingHealth').textContent.includes('MLB: 1 game-result source unavailable'));
assert(node('#gradingHealth').textContent.includes('Affected forecasts stay pending'));
context.fixture.sports.MLB.gradingStatus='CURRENT';vm.runInContext('render()',context);assert.equal(node('#gradingHealth').textContent,'');
console.log('Slip rendering, leg availability, board timing, review flags, expiry and provider errors passed.');

context.fixture.platformFeed.plannedChecks=[{sport:'NFL',checkAt:new Date(now+7200000).toISOString(),games:8},{sport:'MLB',checkAt:new Date(now+3600000).toISOString(),games:1},{sport:'NHL',checkAt:new Date(now-3600000).toISOString(),games:2},{sport:'<NBA>',checkAt:'invalid',games:1}];
vm.runInContext('render()',context);
assert(node('#boardSchedule').innerHTML.includes('Upcoming automatic board checks'));
assert(node('#boardSchedule').innerHTML.indexOf('MLB')<node('#boardSchedule').innerHTML.indexOf('NFL'));
assert(!node('#boardSchedule').innerHTML.includes('NHL'));
assert(!node('#boardSchedule').innerHTML.includes('NBA'));
assert(node('#boardSchedule').innerHTML.includes('8 games'));
assert(node('#boardSchedule').innerHTML.includes('1 game</li>'));
context.fixture.platformFeed.plannedChecks=[];vm.runInContext('render()',context);assert.equal(node('#boardSchedule').innerHTML,'');
console.log('Upcoming board schedule ordering, stale/invalid exclusion and empty state passed.');
